plugins { `java-library` }

dependencies {
    implementation("org.yaml:snakeyaml:2.7")
    implementation("org.xerial:sqlite-jdbc:3.53.4.0")
    implementation("org.mariadb.jdbc:mariadb-java-client:3.5.10") { isTransitive = false }
    implementation("com.maxmind.db:maxmind-db:4.2.0")
    // Supplied at runtime by the proxy (Velocity bundles Gson), so it is not shaded.
    compileOnly("com.google.code.gson:gson:2.10.1")
    testImplementation("com.google.code.gson:gson:2.10.1")
}

tasks.test { useJUnitPlatform { excludeTags("remote-database") } }

// Writes the version from gradle.properties into BuildInfo.VERSION, so it is set in one place.
val generateBuildInfo = tasks.register("generateBuildInfo") {
    val output = layout.buildDirectory.dir("generated/sources/buildinfo")
    val version = project.version.toString()
    inputs.property("version", version)
    outputs.dir(output)
    doLast {
        val file = output.get().file("io/github/origingate/core/BuildInfo.java").asFile
        file.parentFile.mkdirs()
        file.writeText("""
            |package io.github.origingate.core;
            |
            |/** Generated by the build from gradle.properties. */
            |public final class BuildInfo {
            |    public static final String VERSION = "$version";
            |
            |    private BuildInfo() { }
            |}
            |""".trimMargin())
    }
}
sourceSets.main { java.srcDir(generateBuildInfo) }

tasks.processResources {
    from(rootProject.file("THIRD_PARTY_NOTICES.md")) { into("META-INF") }
}

tasks.register<Test>("remoteDatabaseTest") {
    description = "Run opt-in storage tests against a dedicated MySQL/MariaDB database."
    group = "verification"
    testClassesDirs = sourceSets.test.get().output.classesDirs
    classpath = sourceSets.test.get().runtimeClasspath
    useJUnitPlatform { includeTags("remote-database") }
    outputs.upToDateWhen { false }
    doFirst {
        require(System.getenv("OG_TEST_DB_ALLOW_WRITES") == "true") { "Set OG_TEST_DB_ALLOW_WRITES=true for the dedicated test database" }
        require(System.getenv("OG_TEST_DB_DATABASE")?.startsWith("origingate_test_") == true) { "Database must start with origingate_test_" }
    }
}
